-- +goose Up
-- +goose StatementBegin
CREATE TABLE "post" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "title" varchar(255) NOT NULL,
    "body" text NOT NULL,
    "user_id" bigint NOT NULL,
    "created_at" TIMESTAMP NULL,
    "updated_at" TIMESTAMP NULL,
    "deleted_at" TIMESTAMP NULL
);

ALTER TABLE "post" ADD CONSTRAINT "post_user_id_fk_user_id" FOREIGN KEY ("user_id") REFERENCES "user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "post_user_id" ON "post" ("user_id");
COMMIT;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE "post" CASCADE;
COMMIT;
-- +goose StatementEnd
