Name: go-echo-setup

Http:
  Host: localhost
  Port: 5000

Database:
  Engine: postgres
  Name: setup_db
  Host: localhost
  Port: 5432
  Username: setup_user
  Password: setup_password
  TablePrefix: t
  MaxLifetime: 7200
  MaxOpenConns: 150
  MaxIdleConns: 50
  SslMode: disable
  TimeZone: Asia/Jakarta

Cors:
  AllowOrigins:
    - "*"
