Name: go-echo-setup
Secret: foobar

Http:
  Host: 127.0.0.1
  Port: 5000

Database:
  Engine: postgres
  Name: setup_db
  Host: localhost
  Port: 5432
  Username: setup_user
  Password: setup_password
  SslMode: disable
  TimeZone: Asia/Jakarta

Cors:
  AllowOrigins:
    - "*"

Swagger:
  Title: Go Echo Setup Docs
  Description: Collection of Endpoints
  Version: 1.0
  PathUrl: /swagger/*
  DocUrl: /swagger/index.html

Auth:
  Enable: true
  TokenExpired: 7200

Mail:
  Enable: false
  Host: smtp.gmail.com
  Port: 587
  User: example@gmail.com
  Password: secret
  UseTLS: true
  FromEmail: NoReply <noreply@example.com>
