Name: go-echo-setup
Secret: foobar

Http:
  Host: 127.0.0.1
  Port: 5000

Database:
  Engine: postgres
  Name: setup_db
  Host: localhost
  Port: 5432
  Username: setup_user
  Password: setup_password
  TablePrefix: t
  MaxLifetime: 7200
  MaxOpenConns: 150
  MaxIdleConns: 50
  SslMode: disable
  TimeZone: Asia/Jakarta

Cors:
  AllowOrigins:
    - "*"

Swagger:
  Title: "Go Echo Setup Docs"
  Description: "Collection of Endpoints"
  Version: "1.0"
  DocUrl: "/swagger/*"