definitions:
  dto.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  dto.LoginResponse:
    properties:
      access:
        type: string
    type: object
  dto.Pagination:
    properties:
      current:
        type: integer
      page_size:
        type: integer
      total:
        type: integer
    type: object
  dto.PostPaginationResponse:
    properties:
      list:
        items:
          $ref: '#/definitions/dto.PostResponse'
        type: array
      pagination:
        $ref: '#/definitions/dto.Pagination'
    type: object
  dto.PostRequest:
    properties:
      body:
        type: string
      title:
        type: string
    required:
    - body
    - title
    type: object
  dto.PostResponse:
    properties:
      body:
        type: string
      id:
        type: integer
      title:
        type: string
      user:
        $ref: '#/definitions/dto.UserResponse'
    type: object
  dto.RegisterRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  dto.RegisterResponse:
    properties:
      email:
        type: string
      username:
        type: string
    type: object
  dto.UserResponse:
    properties:
      id:
        type: integer
      username:
        type: string
    type: object
  response.Response:
    properties:
      data: {}
      message: {}
    type: object
  response.ValidationError:
    properties:
      field:
        description: Field name that failed validation
        type: string
      message:
        description: Error message describing the validation failure
        type: string
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Login as user to application
      parameters:
      - description: Post
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.LoginResponse'
              type: object
        "400":
          description: bad request
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  items:
                    items:
                      $ref: '#/definitions/response.ValidationError'
                    type: array
                  type: array
              type: object
      summary: Login a User
      tags:
      - auth
  /posts:
    get:
      consumes:
      - application/json
      description: get list several posts
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.PostPaginationResponse'
              type: object
        "400":
          description: bad request
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  items:
                    items:
                      $ref: '#/definitions/response.ValidationError'
                    type: array
                  type: array
              type: object
      summary: List several posts
      tags:
      - post
    post:
      consumes:
      - application/json
      description: Create a post
      parameters:
      - description: Post
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.PostRequest'
      produces:
      - application/json
      responses:
        "201":
          description: created
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.PostResponse'
              type: object
        "400":
          description: bad request
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  items:
                    items:
                      $ref: '#/definitions/response.ValidationError'
                    type: array
                  type: array
              type: object
        "401":
          description: unauthorized
          schema:
            $ref: '#/definitions/response.Response'
        "403":
          description: forbidden
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - BearerAuth: []
      summary: Create a post
      tags:
      - post
  /posts/{id}:
    delete:
      consumes:
      - application/json
      description: perform delete a post
      parameters:
      - description: post id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: no content
        "401":
          description: unauthorized
          schema:
            $ref: '#/definitions/response.Response'
        "403":
          description: forbidden
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - BearerAuth: []
      summary: Delete a post
      tags:
      - post
    get:
      consumes:
      - application/json
      description: get detail a post
      parameters:
      - description: post id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.PostResponse'
              type: object
        "404":
          description: not found
          schema:
            $ref: '#/definitions/response.Response'
      summary: Detail a post
      tags:
      - post
    patch:
      consumes:
      - application/json
      description: Update a post
      parameters:
      - description: Post
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.PostRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: bad request
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  items:
                    items:
                      $ref: '#/definitions/response.ValidationError'
                    type: array
                  type: array
              type: object
        "401":
          description: unauthorized
          schema:
            $ref: '#/definitions/response.Response'
        "403":
          description: forbidden
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - BearerAuth: []
      summary: Update a post
      tags:
      - post
  /register:
    post:
      consumes:
      - application/json
      description: register a new user
      parameters:
      - description: Post
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.RegisterResponse'
              type: object
        "400":
          description: bad request
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  items:
                    items:
                      $ref: '#/definitions/response.ValidationError'
                    type: array
                  type: array
              type: object
      summary: Register a new User
      tags:
      - auth
  /users:
    get:
      consumes:
      - application/json
      description: get list several users
      produces:
      - application/json
      responses: {}
      summary: List several users
      tags:
      - user
  /users/{username}:
    delete:
      consumes:
      - application/json
      description: perform delete a user by username
      parameters:
      - description: Username
        in: path
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Delete a User
      tags:
      - user
    get:
      consumes:
      - application/json
      description: get a user by username
      parameters:
      - description: Username
        in: path
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Get a User
      tags:
      - user
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
